import type { Metadata } from "next";
import { Poppins } from "next/font/google"

import "primereact/resources/themes/lara-light-blue/theme.css";
import Providers from "@/components/Providers";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${poppins.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
